spring:
  datasource:
    username: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
server:
  port: 8080
mongodb:
  databaseName: book_store
  connectionString: mongodb://localhost:27017/book_store
  userHistoryCollectionName: user_history
bookstoreApp:
  security:
    jwt:
      secret: mySuperMegaSecret69
      expirationMs: 86400000
  mongodb:
    collections:
      history:
        books: books_history
        users: users_history
        premarketplace: premarketplace_history
        marketplace: marketplace_history
  report:
    defaultPdfBuilder: ITEXT